import { Space_Grotesk } from "next/font/google";
import AosInit from "./Cx/AosInit";
import "./globals.css";

const spaceGrotesk = Space_Grotesk({
  variable: "--font-space-grotesk",
  subsets: ["latin"],
});

export const metadata = {
  title: "Gravity Motor | MD 111",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${spaceGrotesk.variable} ${spaceGrotesk.className} h-full antialiased`}
    >
      <body className="flex min-h-full flex-col overflow-x-hidden">
        <AosInit />
        {children}
      </body>
    </html>
  );
}
